import 
{   cardTitle,
    getCardObject,
    createDeck
} 
from '@/util/Card'

describe("Card utility functions tests - Card", () => {
    it("should return card title", () => {
        const expectedTitle = "K";

        const actualTitle = cardTitle(13);
        
        expect(actualTitle)
            .toEqual(expectedTitle)
    })
    it("should return card object", () => {
        const expectedCardObject = {
            number: 1,
            title: "A",
            open: true
        }

        const actualCardObject = getCardObject(1, true);

        // id is generated by the getCardObject function this is why I am asserting features one by one

        expect(actualCardObject.number)
            .toEqual(expectedCardObject.number)
        expect(actualCardObject.title)
            .toEqual(expectedCardObject.title)
        expect(actualCardObject.open)
            .toEqual(expectedCardObject.open)
        
    })
    it("should return the randomly generated deck", () => {
        const expectedMainDeckLength = 54;
        const expectedSecondDeckLength = 50;

        const actualDeck = createDeck();

        expect(actualDeck.mainDeck.length)
            .toEqual(expectedMainDeckLength)
        expect(actualDeck.secondDeck.length)
            .toEqual(expectedSecondDeckLength)
    })
})